### ISSUE TITLE
USER STORY: Anonymous submission

### ISSUE THREAD

**Issue by TanyaG10** [datonex/love-running#2]
To **keep my privacy** as a **user**, I can **anonymously vote on the poll**

## Acceptance Criteria:

- The option should be provided as a checkbox

- The checkbox should be “checked” by default

- The option should appear next to the submit button

- After submitting the default submission confirmation should be adjusted to include the user name.

## Tasks

- [ ] Update the view: the poll design (HTML & CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
